### ISSUE TITLE
osu! path doesn't seem to show & autoconnect/disconnect doesn't work

### ISSUE THREAD

**Issue by auroraongithub** [Koltay/osuEscape#4] opened 2022-04-26 02:18 UTC
![image](https://user-images.githubusercontent.com/86182778/165206262-234f7db4-f626-448f-a6b5-f045823c213b.png)
the osu! path not showing despite selecting the osu!.exe file might have some connection with it not working, though i think its just me lol

manual enabling-disabling works though

**Comment by Koltay** [comment] 2022-04-26 16:38
If the manual toggling function works fine, it means the directory is set correctly; as for the display issue, we are still investigating and will review it in the future. May I know your directory for osu! folder?

**Comment by auroraongithub** [comment] 2022-04-26 22:02
> If the manual toggling function works fine, it means the directory is set correctly; as for the display issue, we are still investigating and will review it in the future. May I know your directory for osu! folder?

C:\Users\HP\AppData\Local\osu!\osu!.exe

**Comment by Koltay** [comment] 2022-04-27 12:33
It is clearly an issue caused by a long directory. We have resolved the issue by fixing the properties of the label by enabling the auto ellipse property. This will be fixed in the next release.

(Test case:)
![image](https://user-images.githubusercontent.com/73950784/165518860-d1e9b60a-2508-4aac-9cfb-c82c86641aa5.png)

**Closed as completed by Koltay** 2022-04-27 12:33 UTC
Labels: bug, good first issue
